### ISSUE TITLE
Logo proposal: Nerodia

### ISSUE THREAD

**Issue by baranpirincal** [Volcyy/nerodia#1]
Hi, I can contribute on your project with making a logo design. I examined the project and did not see any logo design. What do you think about it? :grinning: I'm waiting your feedbacks, if you interested we can share our ideas or decisions about design. Have a nice day,good luck! :)

**Comment by Volcyy** [comment]
Hey @baranpirincal, thanks for your interest in the project!
Thank you for suggesting this, but I already have a logo for the project made by a friend, and I'm going to upload it soon. Thanks though!
